name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    name: Test and Build Projects
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [docs, ng-verse]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js

      - name: Run Prettier
        run: npm run format:check

      - name: Run lint
        run: npx ng lint --project=${{ matrix.project }}

      - name: Run tests
        run: npx ng test --no-watch --no-progress --browsers=ChromeHeadless --project=${{ matrix.project }}

      - name: Build project
        run: npx ng build --project=${{ matrix.project }}
